config/routes.rb
Rails.application.routes.draw do
  # resources :charges
  devise_for :users
  root to: 'home#index'
  # get 'home/index'
  get 'card/edit'# card/edit.html.erb画面にアクセス
  post 'home/create'# homeコントローラーのcreateアクション実行
  
  get 'card/destroy'# card/destroy.html.erb画面にアクセス
  put 'home/cancel_subscription'# homeコントローラーのcancel_subscriptionアクション実行

  get 'card/restart'# card/restart.html.erb画面にアクセス
  put 'home/restart_subscription'# homeコントローラーのrestart_subscriptionアクション実行

  get 'card/fin_subscription'# card/fin_subscription.html.erb画面にアクセス
  # post 'home/home_params'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/card_controller.rb
class CardController < ApplicationController
end

app/helpers/card_helper.rb
module CardHelper
end

app/views/card/destroy.html.erb
<div class="text-center">

  <h1>月額課金をキャンセルします</h1>

  <ul>
    <li>
      <%# ボタンを作って、押したら"http://localhost:3000/home/cancel_subscription"にアクセスする %>
      <%# class: 'btn'でボタン化 %>
      <%= button_to '月額課金キャンセル', home_cancel_subscription_path, method: :put, class: "btn btn-primary" %>
      <%# <%= link_to "月額課金キャンセル", home_cancel_subscription_path, class: 'btn btn-default' %>
    </li>
  </ul>

</div>

app/views/card/edit.html.erb
<div class="text-center">

  <h1>月額課金登録</h1>

  <script src="https://js.stripe.com/v3/"></script>
  <%#  %>
  <% publishable_key = Rails.application.secrets.stripe_publishable_key %>
  <%# ******************************************************* %>
  <%# フォーム %>
  <%# 送信した結果をhome/createに送られる %>
  <%# "http://localhost:3000/home/create" %>



  <form action="<%= home_create_path %>" method="post" id="payment-form">
    <div class="form-row">

      <!-- <label for="card-element">クレジットカード</label> -->
      <label for="card-element" class="sr-only">クレジットカード</label>

      <!-- A Stripe Element will be inserted here. -->
      <%# 中央にするbootstrapを適用するために、divを作る %>
      <div class="mx-auto">
        <div id="card-element"></div>
      </div>
      
      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>

    <button class="btn btn-primary">決済処理実行</button>
  </form>

</div>

<%# ******************************************************* %>



<%# ******************************************************* %>
<%# ボタン %>
<script type="text/javascript">
  // Create a Stripe client.
  var stripe = Stripe('<%= publishable_key %>');

  // Create an instance of Elements.
  var elements = stripe.elements();

  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      lineHeight: '18px',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');

  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function(event) {
    // フォームのエラー表示部分を取り出す
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      // エラー文を直接表示
      displayError.textContent = event.error.message;
    } else {
      // エラー文を好きな文字で表示
      displayError.textContent = '';
    }
  });

  // Handle form submission.
  // 上のフォームを取り出す
  var form = document.getElementById('payment-form');

  // submitイベントが働いた時の動き
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    // ストライプトークンを作成
    stripe.createToken(card).then(function(result) {
      // エラーの場合
      if (result.error) {
        // Inform the user if there was an error.
        // フォームのエラー表示部分を取り出す
        var errorElement = document.getElementById('card-errors');
        // エラー文を直接表示
        errorElement.textContent = result.error.message;
      } else {

        // Send the token to your server.
        //カード情報はこの中に入っている
        stripeTokenHandler(result.token);
        
      }
    });
  });
</script>

<%# ******************************************************* %>


<%# ******************************************************* %>
<%# stripeTokenHandler(token)関数 %>
<script type="text/javascript">
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    // 上のフォームを取り出す
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    // フォームにトークンを挿入
    form.appendChild(hiddenInput);

    // Submit the form
    // フォームを送信
    form.submit();
    
  }
</script>
<%# ******************************************************* %>

app/views/card/fin_subscription.html.erb
<%# 月額課金キャンセルや再開が終了したのちに来る画面 %>
<div class="text-center">

  <h1>処理を実行しました</h1>

  <ul>
    <li>
      <%# ボタンを作って、押したら"http://localhost:3000/"にアクセスする %>
      <%# class: 'btn'でボタン化 %>
      <%= link_to "メインに戻る", root_path %>
    </li>
  </ul>

</div>

app/views/card/restart.html.erb
<div class="text-center">

  <h1>月額課金を再開します</h1>

  <ul>
    <li>
      <%# ボタンを作って、押したら"http://localhost:3000/home/restart_subscription"にアクセスする %>
      <%# class: 'btn'でボタン化 %>
      <%= button_to '月額課金再開', home_restart_subscription_path, method: :put, class: "btn btn-primary" %>
      <%# <%= link_to "月額課金再開", home_restart_subscription_path, class: 'btn btn-default' %>
    </li>
  </ul>

</div>